server:
  port: 8081
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/payapp}

jwt:
  secret: ${JWT_SECRET:dev-very-long-secret-min-32-bytes-please-change}
  accessTtlSeconds: 900      # 15 минут
  refreshTtlSeconds: 2592000 # 30 дней

telegram:
  botToken: ${TELEGRAM_BOT_TOKEN:replace-me}
