server:
  port: 8085

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/payapp}

jwt:
  secret: ${JWT_SECRET:dev-very-long-secret-min-32-bytes-please-change}
  accessTtlSeconds: 900
  refreshTtlSeconds: 2592000